  apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: app-flask
        image: localhost:32000/app-flask:latest
        ports:
        - containerPort: 3001
        resources:
          limits:
            memory: "256Mi" # 256 MB
            cpu: "200m"     # 200milli cpu (2. cpu or 20% of cpu)
